Add Dive, SOPS and Tkn as Food
fishworks/fish-food pull request #2092
Opened 2021-12-14 13:42 UTC by oliverbaehler

Adds three new foods to the rig:

  * [https://github.com/wagoodman/dive](https://github.com/wagoodman/dive)
  * [https://github.com/mozilla/sops](https://github.com/mozilla/sops)
  * [https://github.com/tektoncd/cli](https://github.com/tektoncd/cli)

Tested all three foods locally:

```
$ gofish lint Food/dive.lua 
🐠  No errors discovered in 'dive'

$ gofish lint Food/sops.lua 
🐠  No errors discovered in 'sops'

$ gofish lint Food/tektoncd-cli.lua 
🐠  No errors discovered in 'tektoncd-cli'
```

2021-12-14 14:51 UTC, bacongobbler commented
Looks like the tests failed while installing some of the packages. Can you look into that?

2021-12-14 23:30 UTC, arbourd requested changes

2021-12-14 23:30 UTC, arbourd commented on Food/sops.lua
> +                    path = name,
```suggestion
                    path = name .. "-" .. release .. ".darwin",
```
- `name` represents the asset here, which is actually `name .. "-" .. release .. ".darwin"`
- `installpath = "bin/" .. name` will change `sops-v0.0.0.darwin` to `sops`

2021-12-24 05:04 UTC, bacongobbler commented
Closing as inactive. Please reopen when ready for another review. Thanks.

2021-12-24 05:04 UTC, closed without merging